- type: job
  id: BoSWashingtonKnight
  name: job-name-bos-washington-knight
  startingGear: BoSWashingtonKnightGear
  departments:
  - Washington Brotherhood of Steel
  icon: "Warden"
  supervisors: job-name-bos-washington
  canBeAntag: false
  access:
  - Security
  - Armory
  - Maintenance
  - Service
  - Brig
  - External

- type: startingGear
  id: BoSWashingtonKnightGear
  equipment:
    head: ClothingHeadHatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterCoatWarden
    id:
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
  innerclothingskirt: ClothingUniformJumpskirtWarden
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
